---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ffses.kodachi.com
spec:
  group: kodachi.com
  names:
    categories:
    - kodachi-crds
    kind: FFS
    listKind: FFSList
    plural: ffses
    singular: ffs
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: false
    additionalPrinterColumns:
    - jsonPath: .spec.ffs
      name: FFS
      type: string
    - jsonPath: .spec.strength
      name: Strength
      type: string
    schema:
      openAPIV3Schema:
        type: object
        description: FFS
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FFSSpec defines the desired state of FFS
            x-kubernetes-preserve-unknown-fields: true
            required:
            - ffs
            type: object
            properties:
              ffs:
                description: A well-behaving FFS controller will response to any request with an array that contains this string for every FFS resource found.
                type: string
              strength:
                description: The strength of the curse
                type: integer
  - name: v1alpha2
    served: true
    storage: true
    additionalPrinterColumns:
    - jsonPath: .spec.curse
      name: Curse
      type: string
    - jsonPath: .spec.strength
      name: Strength
      type: string
    schema:
      openAPIV3Schema:
        type: object
        description: FFS
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FFSSpec defines the desired state of FFS
            x-kubernetes-preserve-unknown-fields: true
            required:
            - curse
            type: object
            properties:
              curse:
                description: A well-behaving FFS controller will response to any request with an array that contains this string for every FFS resource found.
                type: string
              strength:
                description: The strength of the curse
                type: integer
